IMDSv2 attempt should IMDSv1 fail

diff --git a/ec2_configinit b/ec2_configinit
--- a/ec2_configinit
+++ b/ec2_configinit
@@ -33,7 +33,22 @@ ec2_configinit_run()
 		/usr/local/sbin/configinit $CONFFILE
 		echo .
 	else
-		echo " failed."
+        # If we get here, chances are high that the user has disabled IMDSv1
+        # As such let's attempt to use it
+        pkg install -y curl
+        TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"`
+
+        # Now attempt to fetch the user-data again with the appropriate token
+        curl -o ${CONFFILE} -H "X-aws-ec2-metadata-token: ${TOKEN}" -v ${CONFIGURL}
+        if [ $? = 0 ]; then
+            # Process the user-data.
+            echo .
+            echo -n "Processing EC2 user-data"
+            /usr/local/sbin/configinit $CONFFILE
+            echo .
+        else
+    		echo " failed."
+        fi
 	fi
 
 	# Whether we suceeded or not, delete the temporary file.
